/* THIS FILE IS USED FOR ALL ACTION TYPES ACROSS THE APPLICATION*/

//scheduler
export const BUTTON_CLICKED = 'BUTTON_CLICKED';
export const SET_APPOINTMENT = 'SET_APPOINTMENT';

//modal
export const SET_NAME = 'SET_NAME';
export const SET_TIME = 'SET_TIME';
export const SUBMIT_TIME = 'SUBMIT_TIME';
export const CANCEL_SELECTION = 'CANCEL_SELECTION';


